[package]
name = "recalc"
version = "0.1.0"
authors = ["Ian Liu Rodrigues <ian.liu88@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.0"
pest_derive = "2.0"
rustyline = "*"
